### ISSUE TITLE
Further instructions request.

### ISSUE THREAD

**Issue by alex938** [deadPix3l/CryptSky#6]
Good evening,

Please could someone run through how exactly to execute (encrypt/decrypt functions) the script?

Kind regards,

Alex.

**Comment by deadPix3l** [comment]
This project is not designed to be executed. There is no problem with the code per my testing, and it should run with no issue. BUT i do not condone execution of this project and no help will be provided. If you do run it (please dont!), I provide no warranty that it will work, nor do i accept any liability for the consequences of your actions. If you do, however, find errors (hopefully you are testing in a safe, legal enviroment), please open a new issue and i will address them.
